---
title: "Proposed Sources for a Literature Review - "
author: "Jared Martin"
format: pdf
editor: visual
---

## Document's Purpose

Purpose of this document is to compile and organize scholarly articles relevant to a tree phenology project centered on Denver. The articles listed below are ordered by topical relevance. Most sources were identified through a review of key highlighted references, and all are presented in APA format. Articles italicized indicate those that have already been reviewed.

### General Urban Phenology:

1.  Jochner, S., & Menzel, A. (2015). Urban phenological studies – Past, present, future. Environmental Pollution, 203, 250–261. https://doi.org/10.1016/j.envpol.2015.01.003

2.  (Doesn't seem related but interesting) Anderegg W R, Abatzoglou J T, Anderegg L D, Bielory L, Kinney P L and Ziska L 2021 Anthropogenic climate change is worsening North American pollen seasons Proc. Natl Acad. Sci. 118 e2013284118

3.  Tan P Y and Ismail M R 2014 Building shade affects light environment and urban greenery in high-density residential estates in Singapore Urban For. Urban Greening 13 771–84

4.  Elmore, A. J., Guinn, S. M., Minsley, B. J., & Richardson, A. D. (2012). Landscape controls on the timing of spring, autumn, and growing season length in mid-Atlantic forests. Global Change Biology, 18(2), 656–674. https://doi.org/10.1111/j.1365-2486.2011.02521.x

### Denver Specfic Phenology/climate:

5.  *Crawford, B., Kelsey, K. C., Ibsen, P. C., Rees, A., & Charobee, A. (2024). Intra-urban variations in land surface phenology in a semi-arid environment. Environmental Research Letters. https://doi.org/10.1088/1748-9326/ad9759*

6.  Ibsen P C, Jenerette G D, Dell T, Bagstad K J and Diffendorfer J E 2022 Urban landcover differentially drives day and nighttime air temperature across a semi-arid city Sci. Total Environ. 829 154589

7.  Ibsen P C, Crawford B R, Corro L, Bagstad K J, McNellis B E, Jenerette G D and Diffendorfer J E 2024 Urban tree cover provides consistent mitigation of extreme heat in arid but not humid cities Sustain. Cities Soc. 17 105677

### Tree Phenology:

8.  Brunner, A.M., Varkonyi-Gasic, E., Jones, R.C., 2017. Phase change and phenology in trees. In: Groover, A., Cronk, Q. (Eds.), Comparative and Evolutionary Genomics of Angiosperm Trees. Springer International Publishing, Cham, pp. 227–274. https:// doi.org/10.1007/7397_2016_30.

### Using Planet Scope to Study Phenoplopgical Cycles/Events:

9.  *Alonzo, M., Baker, M.E., Caplan, J.S., Williams, A., Elmore, A.J., 2023. Canopy composition drives variability in urban growing season length more than the heat island effect. Sci. Total Environ. 884, 163818. https://doi.org/10.1016/ j.scitotenv.2023.163818.*

10.  *Sensitivity of Urban tree leaf phenology to precipitation and temperature in a Mediterranean climate city. (Yet to be published will update citation format when published).*

11. Wang, H., Gong, F.-Y., 2024. Quantifying City- and Street-Scale urban tree phenology from Landsat-8, Sentinel-2, and PlanetScope images: a case study in downtown Beijing. Remote Sens 16, 2351. https://doi.org/10.3390/rs16132351.

12. Pan, B., Xiao, X., Luo, S., Pan, L., Yao, Y., Zhang, C., Meng, C., Qin, Y., 2025. Identify and track White flower and leaf phenology of deciduous broadleaf trees in spring with time series PlanetScope images. ISPRS J. Photogramm. Remote Sens 226, 127–145. https://doi.org/10.1016/j.isprsjprs.2025.05.013.

### Effects of Climate Change on Phenology

13. Richardson, A.D., Keenan, T.F., Migliavacca, M., Ryu, Y., Sonnentag, O., Toomey, M., 2013. Climate change, phenology, and phenological control of vegetation feedbacks to the climate system. Agric. For. Meteor. 169, 156–173. https://doi.org/10.1016/ j.agrformet.2012.09.012.

14. Chamberlain C J and Wolkovich E M 2021 Late spring freezes coupled with warming winters alter temperate tree phenology and growth New Phytol. 231 987–95

### Heat Islands

15. Ziter, C.D., Pedersen, E.J., Kucharik, C.J., Turner, M.G., 2019. Scale-dependent interactions between tree canopy cover and impervious surfaces reduce daytime urban heat during summer. Proc. Natl. Acad. Sci. 116, 7575–7580. https://doi.org/ 10.1073/pnas.1817561116.

### Deriving Phenological Events and Cycles

16. Bolton, D.K., Gray, J.M., Melaas, E.K., Moon, M., Eklundh, L., Friedl, M.A., 2020. Continental-scale land surface phenology from harmonized landsat 8 and Sentinel-2 imagery. Remote Sens. Environ. 240, 111685. https://doi.org/10.1016/

17. *Kong, D., McVicar, T. R., Xiao, M., Zhang, Y., Peña‐Arancibia, J. L., Filippa, G., Xie, Y., & Gu, X. (2022). phenofit : An R package for extracting vegetation phenology from time series remote sensing. Methods in Ecology and Evolution, 13(7), 1508–1527. https://doi.org/10.1111/2041-210x.13870*

18. Kong, D., Zhang, Y., Wang, D., Chen, J., & Gu, X. (2020). Photoperiod explains the asynchronization between vegetation carbon phenol- ogy and vegetation greenness phenology. Journal of Geophysical Research: Biogeosciences, 125(8), e2020JG005636. https://doi. org/10.1029/2020JG005636 **Note: Selecting the correct phenology extractinon method based on research purposed. i.e. should the inflection point method be used to calculate SOS and EOS dates.**

### Remote Sensing Applications

19. Furby, S.L., Campbell, N.A., 2001. Calibrating images from different dates to ‘like-value’ digital counts. Remote Sens. Environ. 77, 186–196. https://doi.org/10.1016/S0034- 4257(01)00205-X.

### Machine Learning Applications in Phenological Models

20. Dai, W., Jin, H., Zhang, Y., Liu, T., & Zhou, Z. (2019). Detecting temporal changes in the temperature sensitivity of spring phenology with global warming: Application of machine learning in phenological model. Agricultural and Forest Meteorology, 279, 107702. https://doi.org/10.1016/j.agrformet.2019.107702
