---
title: "Phenological Curve - Alternative to Phenofit"
author: "Jared Martin"
format: html
editor: visual
---

```{r}

library(tidyverse)
library(pracma)
library(oce)
library(minpack.lm)

```

```{r}

read_rds("./raw_extracts/extracted_ndvi_value.rds") -> extracts

```


```{r}

fit_annual_curve <- function(growing_seasons){
  
  elmore_curve <- function(m, t) {
    m[1] + (m[2] - m[7]*t) * ((1/(1+exp((m[3]-t)/m[4]))) - (1/(1+exp((m[5]-t)/m[6]))))
  }
  
  safe_get <- function(x, l, i) {
    if ( length(x) > l) {
      return(NA) # Returns NA if index is out of bounds
      } else if (is.na(x[i])) {
        return(NA)
      } else {
        return(x[i])
      }
    }
  
  len_zero <- function(x){
    if ( length(x) == 0){
      return(c(NA))
      } else {
        return(x)
      }
    }

  get_transitions_doys <- function(bootstrapped_curves, doy, ci = .95, year){
  
   results <- vector("list", ncol(bootstrapped_curves))
  
  for(i in seq(ncol(bootstrapped_curves))){
    
    d1 <- diff(bootstrapped_curves[, i])              
    d2 <- diff(d1)                         
    d1_aligned <- d1[-length(d1)]          
    K      <- d2 / (1 + d1_aligned^2)^(3/2)   
    Kprime <- diff(K)                          
    Kpp    <- diff(Kprime)                     
    doy_Kp <- doy[1:length(Kprime)]
    
    # Local extrema of K' are where K'' changes sign
    sc         <- which(diff(sign(Kpp)) != 0)
    directions <- diff(sign(Kpp))[sc]
    
    # Local maxima of K' (K'' goes + to -) → Greenup, Maturity 
    maxima_doys <- doy_Kp[sc[directions < 0]]
    # Local minima of K' (K'' goes - to +) → Senescence, Dormancy
    minima_doys <- doy_Kp[sc[directions > 0]]
      
    doy_d2 <- doy[1:length(d2)]
    concavity_doys <- doy_d2[which(diff(sign(d2)) != 0)]
    
    concavity_doys <- len_zero(concavity_doys)
    maxima_doys <- len_zero(maxima_doys)
    minima_doys <- len_zero(minima_doys)
    
    peak_doy_boot <- doy[which.max(bootstrapped_curves[, i])]
    
    concavity_spring <- len_zero(concavity_doys[concavity_doys < peak_doy])
    concavity_fall   <- len_zero(concavity_doys[concavity_doys > peak_doy])

    maxima_spring <- len_zero(maxima_doys[maxima_doys < peak_doy])
    minima_fall   <- len_zero(minima_doys[minima_doys > peak_doy])
    
    data.frame(
      Greenup_doy = safe_get(maxima_spring, 2, 1),
      SOS_doy = safe_get(concavity_spring, 1, 1),
      Maturity_doy = safe_get(maxima_spring, 2, 2),
      Senescence_doy = safe_get(minima_fall, 2, 1),
      EOS_doy = safe_get(concavity_fall, 1, 1),
      Dormancy_doy = safe_get(minima_fall, 2, 2),
      Peak_NDVI_doy = peak_doy_boot) -> results[[i]]
  }
   
   do.call(rbind, results) %>%
  summarise(
    across(
      c(Greenup_doy, SOS_doy, Maturity_doy, Senescence_doy,
        EOS_doy, Dormancy_doy, Peak_NDVI_doy),
      list(
        mean  = ~mean(.x, na.rm = TRUE),
        sd    = ~sd(.x,   na.rm = TRUE),
        ci_lo = ~quantile(.x, probs = (1 - ci) / 2,       na.rm = TRUE),
        ci_hi = ~quantile(.x, probs = 1 - (1 - ci) / 2,  na.rm = TRUE)
      ),
      .names = "{.fn}_boot_{.col}"
    )
  ) %>%
  mutate(season = year)

   }

  smooth.spline(growing_seasons$im_doy, growing_seasons$ndvi, df = 7) -> annual_spline

  seq(min(growing_seasons$im_doy), max(growing_seasons$im_doy), by = 1) -> x_daily

  x_daily[x_daily <= 180] -> x_daily_spring
  x_daily[x_daily > 180] -> x_daily_fall

  diff(predict(annual_spline, x_daily_spring)$y) -> dy_spring
  diff(predict(annual_spline, x_daily_fall)$y) -> dy_fall

  x_daily_spring[which.max(dy_spring)] -> sos_doy_est
  x_daily_fall[which.min(dy_fall)] -> eos_doy_est

  x0 <- growing_seasons$im_doy
  y0 <- growing_seasons$ndvi

  m1_idx <- which(x0 < 90 | x0 > 330)
  m1 <- quantile(y0[m1_idx], 0.50)
  m2 <- quantile(y0, 0.99) - m1
  m3 <- sos_doy_est
  m4 <- 10
  m5 <- eos_doy_est
  m6 <- 10
  m7 <- 4

  fit1 <- nlsLM(y0 ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                start = list(a=m1, b=m2, c=m3, d=m4, e=m5, f=m6, g=m7))

  p1 <- fit1$m$getPars()
  w1 <- max(abs(residuals(fit1)))^2 - abs(residuals(fit1))^2

  fit2 <- nlsLM(y0 ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                start = list(a=p1[1], b=p1[2], c=p1[3], d=p1[4], e=p1[5], f=p1[6], g=p1[7]),
                weights = w1)

  p2 <- fit2$m$getPars()
  w2 <- max(abs(residuals(fit2)))^2 - abs(residuals(fit2))^2

  fit3 <- nlsLM(y0 ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                start = list(a=p2[1], b=p2[2], c=p2[3], d=p2[4], e=p2[5], f=p2[6], g=p2[7]),
                weights = w2)

  p3 <- fit3$m$getPars()
  w3 <- max(abs(residuals(fit3)))^2 - abs(residuals(fit3))^2

  fitted_vals <- elmore_curve(p3, x0)
  resids <- y0 - fitted_vals

  pred_mat <- matrix(NA, nrow = max(x0) - min(x0), ncol = 50)

  doy <- seq(min(x0), max(x0))

  pred_mat <- matrix(NA, nrow = length(doy), ncol = 50)

  for (j in seq(50)) {
    yb <- fitted_vals + sample(resids, replace = TRUE)
    try({
      fit_b <- nlsLM(yb ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                     start = list(a=p3[1], b=p3[2], c=p3[3], d=p3[4], e=p3[5], f=p3[6], g=p3[7]),
                     weights = w3)
      pred_mat[, j] <- elmore_curve(fit_b$m$getPars(), doy)
    }, silent = TRUE)
  }

  fitted_curve <- elmore_curve(p3, doy)

    d1 <- diff(fitted_curve)
    d2 <- diff(d1)
    d1_aligned <- d1[-length(d1)]
    K  <- d2 / (1 + d1_aligned^2)^(3/2)
    Kprime <- diff(K)
    Kpp    <- diff(Kprime)
    doy_Kp <- doy[1:length(Kprime)]

    # Local extrema of K' are where K'' changes sign
    sc         <- which(diff(sign(Kpp)) != 0)
    directions <- diff(sign(Kpp))[sc]

    # Local maxima of K' (K'' goes + to -) → Greenup, Maturity
    maxima_doys <- doy_Kp[sc[directions < 0]]
    # Local minima of K' (K'' goes - to +) → Senescence, Dormancy
    minima_doys <- doy_Kp[sc[directions > 0]]

    doy_d2           <- doy[1:length(d2)]
    concavity_doys   <- doy_d2[which(diff(sign(d2)) != 0)]
    
    concavity_doys <- len_zero(concavity_doys)
    maxima_doys <- len_zero(maxima_doys)
    minima_doys <- len_zero(minima_doys)
    
    peak_doy <- doy[which.max(fitted_curve)]

    concavity_spring <- len_zero(concavity_doys[concavity_doys < peak_doy])
    concavity_fall   <- len_zero(concavity_doys[concavity_doys > peak_doy])

    maxima_spring <- len_zero(maxima_doys[maxima_doys < peak_doy])
    minima_fall   <- len_zero(minima_doys[minima_doys > peak_doy])

      data.frame(
        UID = unique(growing_seasons$UID),
        flag = unique(growing_seasons$flag),
        season = unique(growing_seasons$season),
        meth = "Elmore",
        R2 = 1 - (sum((y0 - elmore_curve(p3, x0))^2 / sum((y0 - mean(y0))^2))),
        R = sqrt(1 - (sum((y0 - elmore_curve(p3, x0))^2 / sum((y0 - mean(y0))^2)))),
        RMSE = sqrt(mean((y0 - elmore_curve(p3, x0))^2)),
        Greenup_doy = safe_get(maxima_spring, 2, 1),
        SOS_doy = safe_get(concavity_spring, 1, 1),
        Maturity_doy = safe_get(maxima_spring, 2, 2),
        Senescence_doy = safe_get(minima_fall, 2, 1),
        EOS_doy = safe_get(concavity_fall, 1, 1),
        Dormancy_doy = safe_get(minima_fall, 2, 2),
        Peak_NDVI_doy = peak_doy) %>%
        left_join(get_transitions_doys(pred_mat, doy, year = unique(growing_seasons$season))
              , by = "season")
}

```



```{r, warning = FALSE}

map(seasons, possibly(fit_annual_curve, otherwise = NULL))%>%
  compact() %>%
  bind_rows()

```

```{r}

plot_annual_curve <- function(growing_seasons, show_ci = TRUE, ci = 0.95,
                              show_transitions = TRUE, show_sos_eos = TRUE,
                              show_kprime = FALSE){

  elmore_curve <- function(m, t) {
    m[1] + (m[2] - m[7]*t) * ((1/(1+exp((m[3]-t)/m[4]))) - (1/(1+exp((m[5]-t)/m[6]))))
  }

  get_transitions_doys <- function(bootstrapped_curves, doy, ci = .95, year){

    results <- vector("list", ncol(bootstrapped_curves))

    for(i in seq(ncol(bootstrapped_curves))){

      d1         <- diff(bootstrapped_curves[, i])
      d2         <- diff(d1)
      d1_aligned <- d1[-length(d1)]

      K      <- d2 / (1 + d1_aligned^2)^(3/2)
      Kprime <- diff(K)
      Kpp    <- diff(Kprime)
      doy_Kp <- doy[1:length(Kprime)]

      sc         <- which(diff(sign(Kpp)) != 0)
      directions <- diff(sign(Kpp))[sc]

      maxima_doys <- doy_Kp[sc[directions < 0]]
      minima_doys <- doy_Kp[sc[directions > 0]]

      peak_doy_boot <- doy[which.max(bootstrapped_curves[, i])]

      maxima_spring <- maxima_doys[maxima_doys < peak_doy_boot]
      minima_fall   <- minima_doys[minima_doys > peak_doy_boot]

      doy_d2           <- doy[1:length(d2)]
      concavity_doys   <- doy_d2[which(diff(sign(d2)) != 0)]
      concavity_spring <- concavity_doys[concavity_doys < peak_doy_boot]
      concavity_fall   <- concavity_doys[concavity_doys > peak_doy_boot]

      data.frame(
        Greenup_doy    = maxima_spring[1],
        SOS_doy        = tail(concavity_spring, 1),
        Maturity_doy   = maxima_spring[2],
        Senescence_doy = minima_fall[1],
        EOS_doy        = concavity_fall[1],
        Dormancy_doy   = minima_fall[2],
        Peak_NDVI_doy  = peak_doy_boot
      ) -> results[[i]]
    }

    do.call(rbind, results) %>%
      summarise(
        across(
          c(Greenup_doy, SOS_doy, Maturity_doy, Senescence_doy,
            EOS_doy, Dormancy_doy, Peak_NDVI_doy),
          list(
            mean  = ~mean(.x, na.rm = TRUE),
            sd    = ~sd(.x,   na.rm = TRUE),
            ci_lo = ~quantile(.x, probs = (1 - ci) / 2,      na.rm = TRUE),
            ci_hi = ~quantile(.x, probs = 1 - (1 - ci) / 2, na.rm = TRUE)
          ),
          .names = "{.fn}_boot_{.col}"
        )
      ) %>%
      mutate(season = year)
  }

  smooth.spline(growing_seasons$im_doy, growing_seasons$ndvi, df = 7) -> annual_spline
  seq(min(growing_seasons$im_doy), max(growing_seasons$im_doy), by = 1) -> x_daily
  x_daily[x_daily <= 180] -> x_daily_spring
  x_daily[x_daily > 180]  -> x_daily_fall
  diff(predict(annual_spline, x_daily_spring)$y) -> dy_spring
  diff(predict(annual_spline, x_daily_fall)$y)   -> dy_fall

  x_daily_spring[which.max(dy_spring)] -> sos_doy_est
  x_daily_fall[which.min(dy_fall)]     -> eos_doy_est
  x0 <- growing_seasons$im_doy
  y0 <- growing_seasons$ndvi

  m1_idx <- which(x0 < 90 | x0 > 330)
  m1 <- quantile(y0[m1_idx], 0.50)
  m2 <- quantile(y0, 0.99) - m1
  m3 <- sos_doy_est
  m4 <- 10
  m5 <- eos_doy_est
  m6 <- 10
  m7 <- 4

  fit1 <- nlsLM(y0 ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                start = list(a=m1, b=m2, c=m3, d=m4, e=m5, f=m6, g=m7))
  p1 <- fit1$m$getPars()
  w1 <- max(abs(residuals(fit1)))^2 - abs(residuals(fit1))^2

  fit2 <- nlsLM(y0 ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                start = list(a=p1[1], b=p1[2], c=p1[3], d=p1[4], e=p1[5], f=p1[6], g=p1[7]),
                weights = w1)
  p2 <- fit2$m$getPars()
  w2 <- max(abs(residuals(fit2)))^2 - abs(residuals(fit2))^2

  fit3 <- nlsLM(y0 ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                start = list(a=p2[1], b=p2[2], c=p2[3], d=p2[4], e=p2[5], f=p2[6], g=p2[7]),
                weights = w2)
  p3 <- fit3$m$getPars()
  w3 <- max(abs(residuals(fit3)))^2 - abs(residuals(fit3))^2

  fitted_vals <- elmore_curve(p3, x0)
  resids      <- y0 - fitted_vals

  doy      <- seq(min(x0), max(x0))
  pred_mat <- matrix(NA, nrow = length(doy), ncol = 50)

  for (j in seq(50)) {
    yb <- fitted_vals + sample(resids, replace = TRUE)
    try({
      fit_b <- nlsLM(yb ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                     start = list(a=p3[1], b=p3[2], c=p3[3], d=p3[4], e=p3[5], f=p3[6], g=p3[7]),
                     weights = w3)
      pred_mat[, j] <- elmore_curve(fit_b$m$getPars(), doy)
    }, silent = TRUE)
  }

  fitted_curve <- elmore_curve(p3, doy)

  d1         <- diff(fitted_curve)
  d2         <- diff(d1)
  d1_aligned <- d1[-length(d1)]

  K      <- d2 / (1 + d1_aligned^2)^(3/2)
  Kprime <- diff(K)
  Kpp    <- diff(Kprime)
  doy_Kp <- doy[1:length(Kprime)]

  sc         <- which(diff(sign(Kpp)) != 0)
  directions <- diff(sign(Kpp))[sc]

  maxima_doys <- doy_Kp[sc[directions < 0]]
  minima_doys <- doy_Kp[sc[directions > 0]]

  peak_doy <- doy[which.max(fitted_curve)]

  maxima_spring <- maxima_doys[maxima_doys < peak_doy]
  minima_fall   <- minima_doys[minima_doys > peak_doy]

  doy_d2           <- doy[1:length(d2)]
  concavity_doys   <- doy_d2[which(diff(sign(d2)) != 0)]
  concavity_spring <- concavity_doys[concavity_doys < peak_doy]
  concavity_fall   <- concavity_doys[concavity_doys > peak_doy]
  SOS_doy <- tail(concavity_spring, 1)
  EOS_doy <- concavity_fall[1]

  Greenup_doy    <- maxima_spring[1]
  Maturity_doy   <- maxima_spring[2]
  Senescence_doy <- minima_fall[1]
  Dormancy_doy   <- minima_fall[2]
  transition_doys <- c(Greenup_doy, Maturity_doy, Senescence_doy, Dormancy_doy)

  ci_lo <- apply(pred_mat, 1, quantile, probs = (1 - ci) / 2,      na.rm = TRUE)
  ci_hi <- apply(pred_mat, 1, quantile, probs = 1 - (1 - ci) / 2, na.rm = TRUE)

  if (show_kprime) par(mfrow = c(2, 1), mar = c(3, 4, 3, 1))

  plot(x0, y0, pch = 16, col = "gray50",
       xlab = "DOY", ylab = "NDVI",
       main = paste("UID", unique(growing_seasons$UID),
                    "- Season", unique(growing_seasons$season)))

  if (show_ci) {
    polygon(c(doy, rev(doy)), c(ci_lo, rev(ci_hi)),
            col = rgb(0, 0.5, 0, 0.2), border = NA)
  }

  lines(doy, fitted_curve, col = "darkgreen", lwd = 2)
  abline(v = peak_doy, col = "darkgreen", lty = 2)

  if (show_transitions) {
    abline(v = transition_doys, col = "blue", lty = 2, lwd = 1.5)
        text(x = transition_doys,
         y = max(y0, na.rm = TRUE),
         labels = c(paste0("Greenup: ",    Greenup_doy),
                    paste0("Maturity: ",   Maturity_doy),
                    paste0("Senescence: ", Senescence_doy),
                    paste0("Dormancy: ",   Dormancy_doy)),
         col = "blue", cex = 0.7, srt = 90, adj = c(1.1, -0.3))
  }

  if (show_sos_eos) {
    abline(v = c(SOS_doy, EOS_doy), col = "red", lty = 2, lwd = 1.5)
        text(x = c(SOS_doy, EOS_doy),
         y = max(y0, na.rm = TRUE) * 0.9,
         labels = c(paste0("SOS: ", SOS_doy),
                    paste0("EOS: ", EOS_doy)),
         col = "red", cex = 0.7, srt = 90, adj = c(1.1, -0.3))
  }

  if (show_transitions | show_sos_eos) {
    legend("topright",
           legend = c(
             if (show_transitions) "Inflection",
             if (show_sos_eos)     "SOS/EOS",
             "Peak NDVI"),
           col = c(
             if (show_transitions) "blue",
             if (show_sos_eos)     "red",
             "darkgreen"),
           lty = 2, lwd = 1.5, cex = 0.7, bty = "n")
  }

  if (show_kprime) {
    plot(doy_Kp, Kprime, type = "l", col = "purple", lwd = 2,
         xlab = "DOY", ylab = "K' (Rate of Curvature Change)",
         main = "Rate of Change of Curvature (K')")
    abline(h = 0, lty = 2, col = "gray50")
    if (show_transitions) abline(v = transition_doys,      col = "blue", lty = 2, lwd = 1.5)
    if (show_sos_eos)     abline(v = c(SOS_doy, EOS_doy), col = "red",  lty = 2, lwd = 1.5)
    par(mfrow = c(1, 1))
  }
}

```


```{r}

plot_annual_curve(seasons[[2]], show_kprime = TRUE, show_transitions = TRUE)

```

```{r, warning=FALSE}

fix_hex_id <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  
  # Recover 24eN from 2.40E+N pattern (handles both 2.4e+N and 2.40e+N)
  sci_idx <- grepl("^2\\.40?e\\+0?([0-9]+)$", x, ignore.case = TRUE)
  x[sci_idx] <- paste0("24e", sub("^2\\.40?e\\+0?([0-9]+)$", "\\1",
                                   x[sci_idx], ignore.case = TRUE))
  
  # Null out anything else still in scientific notation
  x[grepl("^[0-9.]+e[+-][0-9]+$", x, ignore.case = TRUE) & !sci_idx] <- NA_character_
  x[tolower(x) %in% c("0", "na", "")] <- NA_character_
  
  tolower(x)
}

```


```{r, warning=FALSE}

bind_rows(read_csv("./metadata/pss4_metadata_Denver_sensitivity_2018_2024(in).csv"),
          read_csv("./metadata/pss4_metadata_Denver_2024_2025(in).csv") ) %>% 
  mutate(date = as.Date(date, format = "%m/%d/%Y"),
         time = stringr::str_pad(as.character(time), 6, pad = "0"),
         date = as_date(date),
         im_date_time = as.POSIXct(paste(date, time),
                                   format="%Y-%m-%d %H%M%S",
                                   tz = "UTC")) %>% 
  select(im_date_time, pss4_instrument) -> meta_data

extracts %>% 
  filter(ndvi >= 0) %>% 
  left_join(meta_data, by = "im_date_time") %>% 
  mutate(instrument_clean = fix_hex_id(pss4_instrument),
    sensor_gen = case_when(
      grepl("^0[ef][0-9a-f]{2}$|^10[0-9a-f]{2}$", instrument_clean) ~ "PS2.SD",
      grepl("^2[2345]", instrument_clean) ~ "PSB.SD",
      TRUE ~ "PS2.SD"),
    doy = yday(im_date),
    month = month(im_date, label = TRUE)) -> extracts_sensor_gen 

extracts_sensor_gen %>% 
  slice_sample(n = 100000) -> spline_sample

loess_overall <- loess(ndvi ~ doy, data = spline_sample, span = 0.3)  # <- was dspline_sample
loess_ps2 <- loess(ndvi ~ doy, data = filter(spline_sample, sensor_gen == "PS2.SD"), span = 0.3)
loess_psb <- loess(ndvi ~ doy, data = filter(spline_sample, sensor_gen == "PSB.SD"), span = 0.3)

# Step 3: build DOY lookup table — 365 predictions instead of 17M
tibble(doy = 1:366) %>%
  mutate(fitted_overall = predict(loess_overall, newdata = data.frame(doy = doy)),
    fitted_ps2 = predict(loess_ps2, newdata = data.frame(doy = doy)),
    fitted_psb = predict(loess_psb, newdata = data.frame(doy = doy)),
    offset_ps2 = fitted_overall - fitted_ps2,
    offset_psb = fitted_overall - fitted_psb) %>%
  select(doy, offset_ps2, offset_psb) %>% 
  right_join(extracts_sensor_gen %>% 
      select(-any_of(c("offset_ps2", "offset_psb", "ndvi_normalized"))),  by = "doy") %>%
  mutate(ndvi_normalized = case_when(sensor_gen == "PS2.SD" ~ ndvi + offset_ps2,
                                     sensor_gen == "PSB.SD" ~ ndvi + offset_psb)) -> normalized_ndvi_extracts

```

```{r}

growing_season <- function(ndvi_data, ndvi_obs, df = 30, maxtroughhight = .3, 
                           mintroughdistance = 300, max_season_length = 380){
  
  ndvi_data %>% 
    pull({{ ndvi_obs }}) -> y_vals
  
  smooth.spline(as.numeric(ndvi_data$im_date), y_vals, df = df) -> sm 

  seq(min(as.numeric(ndvi_data$im_date)), 
      max(as.numeric(ndvi_data$im_date)), 
      by = 1) -> x_daily 

  predict(sm, x_daily)$y -> y_smooth 
  
  findpeaks(
    -y_smooth,
    minpeakdistance = mintroughdistance,
    minpeakheight = -maxtroughhight) -> troughs
  
  sort(as.Date(x_daily[troughs[, 2]], origin = "1970-01-01")) -> trough_dates 
  
  c(min(ndvi_data$im_date), trough_dates) -> trough_dates 
  
  seasons <- list()
  
  for (i in seq_along(trough_dates[-length(trough_dates)])) {
    
    as.numeric(trough_dates[i+1] - trough_dates[i]) -> gap 
    
    if (gap < max_season_length) {
      trough_dates[i] -> season_start 
      trough_dates[i + 1] -> season_end
      
      ndvi_data %>%
        filter(im_date >= season_start & im_date < season_end) %>%
        mutate(season = year(season_start),
               flag = paste0(lubridate::year(season_start), "_", 1))%>% 
        mutate(base_date = date(str_c(season,"-","01","-","01")),
               im_doy = as.numeric(difftime(im_date, base_date, units = "days"))) -> seasons[[i]] 
      }
    }
   return(seasons)
  }

# growing_season(extracts_samp, ndvi_obs = ndvi_normalized, maxtroughhight = .4) #use example 

```

```{r}

plot_growing_season <- function(ndvi_data, ndvi_obs , df = 30, maxtroughhight = .3, 
                           mintroughdistance = 300, max_season_length = 380){
  
  ndvi_data %>% 
    pull({{ ndvi_obs }}) -> y_vals
  
  smooth.spline(as.numeric(ndvi_data$im_date), 
              y_vals, 
              df = df) -> sm 

  seq(min(as.numeric(ndvi_data$im_date)), 
      max(as.numeric(ndvi_data$im_date)), 
      by = 1) -> x_daily 

  predict(sm, x_daily)$y -> y_smooth 
  
  findpeaks(
    -y_smooth,
    minpeakdistance = mintroughdistance,
    minpeakheight = -maxtroughhight) -> troughs
  
  sort(as.Date(x_daily[troughs[, 2]], origin = "1970-01-01")) -> trough_dates 
  
  c(min(ndvi_data$im_date), trough_dates) -> trough_dates 
  
  plot(extracts_samp$im_date, extracts_samp$ndvi)

  lines(sm, col = "red")
  lines(as.Date(x_daily, origin = "1970-01-01"), y_smooth, col = "red")
  abline(v = as.numeric(trough_dates), col = "blue", lty = 2)
  
  }

# plot_growing_season(extracts_samp, ndvi_obs = ndvi, maxtroughhight = .4) #use example 

```


```{r}

fit_annual_curve <- function(growing_seasons, ndvi_obs){
  
  elmore_curve <- function(m, t) {
    m[1] + (m[2] - m[7]*t) * ((1/(1+exp((m[3]-t)/m[4]))) - (1/(1+exp((m[5]-t)/m[6]))))
  }
  
  safe_get <- function(x, l, i) {
    if ( length(x) > l) {
      return(NA) # Returns NA if index is out of bounds
      } else if (is.na(x[i])) {
        return(NA)
      } else {
        return(x[i])
      }
    }
  
  len_zero <- function(x){
    if ( length(x) == 0){
      return(c(NA))
      } else {
        return(x)
        }
    }

  get_transitions_doys <- function(bootstrapped_curves, doy, ci = .95, year){
  
   results <- vector("list", ncol(bootstrapped_curves))
  
  for(i in seq(ncol(bootstrapped_curves))){
    
    d1 <- diff(bootstrapped_curves[, i])              
    d2 <- diff(d1)                         
    d1_aligned <- d1[-length(d1)]          
    K      <- d2 / (1 + d1_aligned^2)^(3/2)   
    Kprime <- diff(K)                          
    Kpp    <- diff(Kprime)                     
    doy_Kp <- doy[1:length(Kprime)]
    
    # Local extrema of K' are where K'' changes sign
    sc         <- which(diff(sign(Kpp)) != 0)
    directions <- diff(sign(Kpp))[sc]
    
    # Local maxima of K' (K'' goes + to -) → Greenup, Maturity 
    maxima_doys <- doy_Kp[sc[directions < 0]]
    # Local minima of K' (K'' goes - to +) → Senescence, Dormancy
    minima_doys <- doy_Kp[sc[directions > 0]]
      
    doy_d2 <- doy[1:length(d2)]
    concavity_doys <- doy_d2[which(diff(sign(d2)) != 0)]
    
    concavity_doys <- len_zero(concavity_doys)
    maxima_doys <- len_zero(maxima_doys)
    minima_doys <- len_zero(minima_doys)
    
    peak_doy_boot <- doy[which.max(bootstrapped_curves[, i])]
    
    concavity_spring <- len_zero(concavity_doys[concavity_doys < peak_doy])
    concavity_fall   <- len_zero(concavity_doys[concavity_doys > peak_doy])

    maxima_spring <- len_zero(maxima_doys[maxima_doys < peak_doy])
    minima_fall   <- len_zero(minima_doys[minima_doys > peak_doy])
    
    data.frame(
      Greenup_doy = safe_get(maxima_spring, 2, 1),
      SOS_doy = safe_get(concavity_spring, 1, 1),
      Maturity_doy = safe_get(maxima_spring, 2, 2),
      Senescence_doy = safe_get(minima_fall, 2, 1),
      EOS_doy = safe_get(concavity_fall, 1, 1),
      Dormancy_doy = safe_get(minima_fall, 2, 2),
      Peak_NDVI_doy = peak_doy_boot) -> results[[i]]
  }
   
   do.call(rbind, results) %>%
  summarise(
    across(
      c(Greenup_doy, SOS_doy, Maturity_doy, Senescence_doy,
        EOS_doy, Dormancy_doy, Peak_NDVI_doy),
      list(
        mean  = ~mean(.x, na.rm = TRUE),
        sd    = ~sd(.x,   na.rm = TRUE),
        ci_lo = ~quantile(.x, probs = (1 - ci) / 2,       na.rm = TRUE),
        ci_hi = ~quantile(.x, probs = 1 - (1 - ci) / 2,  na.rm = TRUE)
      ),
      .names = "{.fn}_boot_{.col}"
    )
  ) %>%
  mutate(season = year)

  }
  
  growing_seasons %>% 
    pull({{ ndvi_obs }}) -> y_vals

  smooth.spline(growing_seasons$im_doy, y_vals, df = 7) -> annual_spline

  seq(min(growing_seasons$im_doy), max(growing_seasons$im_doy), by = 1) -> x_daily

  x_daily[x_daily <= 180] -> x_daily_spring
  x_daily[x_daily > 180] -> x_daily_fall

  diff(predict(annual_spline, x_daily_spring)$y) -> dy_spring
  diff(predict(annual_spline, x_daily_fall)$y) -> dy_fall

  x_daily_spring[which.max(dy_spring)] -> sos_doy_est
  x_daily_fall[which.min(dy_fall)] -> eos_doy_est

  x0 <- growing_seasons$im_doy
  y0 <- y_vals

  m1_idx <- which(x0 < 90 | x0 > 330)
  m1 <- quantile(y0[m1_idx], 0.50)
  m2 <- quantile(y0, 0.99) - m1
  m3 <- sos_doy_est
  m4 <- 10
  m5 <- eos_doy_est
  m6 <- 10
  m7 <- 4

  fit1 <- nlsLM(y0 ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                start = list(a=m1, b=m2, c=m3, d=m4, e=m5, f=m6, g=m7))

  p1 <- fit1$m$getPars()
  w1 <- max(abs(residuals(fit1)))^2 - abs(residuals(fit1))^2

  fit2 <- nlsLM(y0 ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                start = list(a=p1[1], b=p1[2], c=p1[3], d=p1[4], e=p1[5], f=p1[6], g=p1[7]),
                weights = w1)

  p2 <- fit2$m$getPars()
  w2 <- max(abs(residuals(fit2)))^2 - abs(residuals(fit2))^2

  fit3 <- nlsLM(y0 ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                start = list(a=p2[1], b=p2[2], c=p2[3], d=p2[4], e=p2[5], f=p2[6], g=p2[7]),
                weights = w2)

  p3 <- fit3$m$getPars()
  w3 <- max(abs(residuals(fit3)))^2 - abs(residuals(fit3))^2

  fitted_vals <- elmore_curve(p3, x0)
  resids <- y0 - fitted_vals

  pred_mat <- matrix(NA, nrow = max(x0) - min(x0), ncol = 50)

  doy <- seq(min(x0), max(x0))

  pred_mat <- matrix(NA, nrow = length(doy), ncol = 50)

  for (j in seq(50)) {
    yb <- fitted_vals + sample(resids, replace = TRUE)
    try({
      fit_b <- nlsLM(yb ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                     start = list(a=p3[1], b=p3[2], c=p3[3], d=p3[4], e=p3[5], f=p3[6], g=p3[7]),
                     weights = w3)
      pred_mat[, j] <- elmore_curve(fit_b$m$getPars(), doy)
    }, silent = TRUE)
  }

  fitted_curve <- elmore_curve(p3, doy)

    d1 <- diff(fitted_curve)
    d2 <- diff(d1)
    d1_aligned <- d1[-length(d1)]
    K  <- d2 / (1 + d1_aligned^2)^(3/2)
    Kprime <- diff(K)
    Kpp    <- diff(Kprime)
    doy_Kp <- doy[1:length(Kprime)]

    # Local extrema of K' are where K'' changes sign
    sc         <- which(diff(sign(Kpp)) != 0)
    directions <- diff(sign(Kpp))[sc]

    # Local maxima of K' (K'' goes + to -) → Greenup, Maturity
    maxima_doys <- doy_Kp[sc[directions < 0]]
    # Local minima of K' (K'' goes - to +) → Senescence, Dormancy
    minima_doys <- doy_Kp[sc[directions > 0]]

    doy_d2           <- doy[1:length(d2)]
    concavity_doys   <- doy_d2[which(diff(sign(d2)) != 0)]
    
    concavity_doys <- len_zero(concavity_doys)
    maxima_doys <- len_zero(maxima_doys)
    minima_doys <- len_zero(minima_doys)
    
    peak_doy <- doy[which.max(fitted_curve)]

    concavity_spring <- len_zero(concavity_doys[concavity_doys < peak_doy])
    concavity_fall   <- len_zero(concavity_doys[concavity_doys > peak_doy])

    maxima_spring <- len_zero(maxima_doys[maxima_doys < peak_doy])
    minima_fall   <- len_zero(minima_doys[minima_doys > peak_doy])

      data.frame(
        UID = unique(growing_seasons$UID),
        flag = unique(growing_seasons$flag),
        season = unique(growing_seasons$season),
        meth = "Elmore",
        R2 = 1 - (sum((y0 - elmore_curve(p3, x0))^2 / sum((y0 - mean(y0))^2))),
        R = sqrt(1 - (sum((y0 - elmore_curve(p3, x0))^2 / sum((y0 - mean(y0))^2)))),
        RMSE = sqrt(mean((y0 - elmore_curve(p3, x0))^2)),
        Greenup_doy = safe_get(maxima_spring, 2, 1),
        SOS_doy = safe_get(concavity_spring, 1, 1),
        Maturity_doy = safe_get(maxima_spring, 2, 2),
        Senescence_doy = safe_get(minima_fall, 2, 1),
        EOS_doy = safe_get(concavity_fall, 1, 1),
        Dormancy_doy = safe_get(minima_fall, 2, 2),
        Peak_NDVI_doy = peak_doy) %>%
        left_join(get_transitions_doys(pred_mat, doy, year = unique(growing_seasons$season))
              , by = "season")
}

# fit_annual_curve(seasons[[2]], ndvi_obs = ndvi_normalized) # use example

```


```{r}

plot_annual_curve <- function(growing_seasons, ndvi_obs, show_ci = TRUE, ci = 0.95,
                              show_transitions = TRUE, show_sos_eos = TRUE,
                              show_kprime = FALSE){

  elmore_curve <- function(m, t) {
    m[1] + (m[2] - m[7]*t) * ((1/(1+exp((m[3]-t)/m[4]))) - (1/(1+exp((m[5]-t)/m[6]))))
  }

  get_transitions_doys <- function(bootstrapped_curves, doy, ci = .95, year){

    results <- vector("list", ncol(bootstrapped_curves))

    for(i in seq(ncol(bootstrapped_curves))){

      d1         <- diff(bootstrapped_curves[, i])
      d2         <- diff(d1)
      d1_aligned <- d1[-length(d1)]

      K      <- d2 / (1 + d1_aligned^2)^(3/2)
      Kprime <- diff(K)
      Kpp    <- diff(Kprime)
      doy_Kp <- doy[1:length(Kprime)]

      sc         <- which(diff(sign(Kpp)) != 0)
      directions <- diff(sign(Kpp))[sc]

      maxima_doys <- doy_Kp[sc[directions < 0]]
      minima_doys <- doy_Kp[sc[directions > 0]]

      peak_doy_boot <- doy[which.max(bootstrapped_curves[, i])]

      maxima_spring <- maxima_doys[maxima_doys < peak_doy_boot]
      minima_fall   <- minima_doys[minima_doys > peak_doy_boot]

      doy_d2           <- doy[1:length(d2)]
      concavity_doys   <- doy_d2[which(diff(sign(d2)) != 0)]
      concavity_spring <- concavity_doys[concavity_doys < peak_doy_boot]
      concavity_fall   <- concavity_doys[concavity_doys > peak_doy_boot]

      data.frame(
        Greenup_doy    = maxima_spring[1],
        SOS_doy        = tail(concavity_spring, 1),
        Maturity_doy   = maxima_spring[2],
        Senescence_doy = minima_fall[1],
        EOS_doy        = concavity_fall[1],
        Dormancy_doy   = minima_fall[2],
        Peak_NDVI_doy  = peak_doy_boot
      ) -> results[[i]]
    }

    do.call(rbind, results) %>%
      summarise(
        across(
          c(Greenup_doy, SOS_doy, Maturity_doy, Senescence_doy,
            EOS_doy, Dormancy_doy, Peak_NDVI_doy),
          list(
            mean  = ~mean(.x, na.rm = TRUE),
            sd    = ~sd(.x,   na.rm = TRUE),
            ci_lo = ~quantile(.x, probs = (1 - ci) / 2,      na.rm = TRUE),
            ci_hi = ~quantile(.x, probs = 1 - (1 - ci) / 2, na.rm = TRUE)
          ),
          .names = "{.fn}_boot_{.col}"
        )
      ) %>%
      mutate(season = year)
  }

  growing_seasons %>% 
    pull({{ ndvi_obs }}) -> y_vals
  
  smooth.spline(growing_seasons$im_doy, y_vals, df = 7) -> annual_spline
  seq(min(growing_seasons$im_doy), max(growing_seasons$im_doy), by = 1) -> x_daily
  x_daily[x_daily <= 180] -> x_daily_spring
  x_daily[x_daily > 180]  -> x_daily_fall
  diff(predict(annual_spline, x_daily_spring)$y) -> dy_spring
  diff(predict(annual_spline, x_daily_fall)$y)   -> dy_fall

  x_daily_spring[which.max(dy_spring)] -> sos_doy_est
  x_daily_fall[which.min(dy_fall)]     -> eos_doy_est
  x0 <- growing_seasons$im_doy
  y0 <- y_vals

  m1_idx <- which(x0 < 90 | x0 > 330)
  m1 <- quantile(y0[m1_idx], 0.50)
  m2 <- quantile(y0, 0.99) - m1
  m3 <- sos_doy_est
  m4 <- 10
  m5 <- eos_doy_est
  m6 <- 10
  m7 <- 4

  fit1 <- nlsLM(y0 ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                start = list(a=m1, b=m2, c=m3, d=m4, e=m5, f=m6, g=m7))
  p1 <- fit1$m$getPars()
  w1 <- max(abs(residuals(fit1)))^2 - abs(residuals(fit1))^2

  fit2 <- nlsLM(y0 ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                start = list(a=p1[1], b=p1[2], c=p1[3], d=p1[4], e=p1[5], f=p1[6], g=p1[7]),
                weights = w1)
  p2 <- fit2$m$getPars()
  w2 <- max(abs(residuals(fit2)))^2 - abs(residuals(fit2))^2

  fit3 <- nlsLM(y0 ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                start = list(a=p2[1], b=p2[2], c=p2[3], d=p2[4], e=p2[5], f=p2[6], g=p2[7]),
                weights = w2)
  p3 <- fit3$m$getPars()
  w3 <- max(abs(residuals(fit3)))^2 - abs(residuals(fit3))^2

  fitted_vals <- elmore_curve(p3, x0)
  resids      <- y0 - fitted_vals

  doy      <- seq(min(x0), max(x0))
  pred_mat <- matrix(NA, nrow = length(doy), ncol = 50)

  for (j in seq(50)) {
    yb <- fitted_vals + sample(resids, replace = TRUE)
    try({
      fit_b <- nlsLM(yb ~ a + (b - g*x0) * ((1/(1+exp((c-x0)/d))) - (1/(1+exp((e-x0)/f)))),
                     start = list(a=p3[1], b=p3[2], c=p3[3], d=p3[4], e=p3[5], f=p3[6], g=p3[7]),
                     weights = w3)
      pred_mat[, j] <- elmore_curve(fit_b$m$getPars(), doy)
    }, silent = TRUE)
  }

  fitted_curve <- elmore_curve(p3, doy)

  d1         <- diff(fitted_curve)
  d2         <- diff(d1)
  d1_aligned <- d1[-length(d1)]

  K      <- d2 / (1 + d1_aligned^2)^(3/2)
  Kprime <- diff(K)
  Kpp    <- diff(Kprime)
  doy_Kp <- doy[1:length(Kprime)]

  sc         <- which(diff(sign(Kpp)) != 0)
  directions <- diff(sign(Kpp))[sc]

  maxima_doys <- doy_Kp[sc[directions < 0]]
  minima_doys <- doy_Kp[sc[directions > 0]]

  peak_doy <- doy[which.max(fitted_curve)]

  maxima_spring <- maxima_doys[maxima_doys < peak_doy]
  minima_fall   <- minima_doys[minima_doys > peak_doy]

  doy_d2           <- doy[1:length(d2)]
  concavity_doys   <- doy_d2[which(diff(sign(d2)) != 0)]
  concavity_spring <- concavity_doys[concavity_doys < peak_doy]
  concavity_fall   <- concavity_doys[concavity_doys > peak_doy]
  SOS_doy <- tail(concavity_spring, 1)
  EOS_doy <- concavity_fall[1]

  Greenup_doy    <- maxima_spring[1]
  Maturity_doy   <- maxima_spring[2]
  Senescence_doy <- minima_fall[1]
  Dormancy_doy   <- minima_fall[2]
  transition_doys <- c(Greenup_doy, Maturity_doy, Senescence_doy, Dormancy_doy)

  ci_lo <- apply(pred_mat, 1, quantile, probs = (1 - ci) / 2,      na.rm = TRUE)
  ci_hi <- apply(pred_mat, 1, quantile, probs = 1 - (1 - ci) / 2, na.rm = TRUE)

  if (show_kprime) par(mfrow = c(2, 1), mar = c(3, 4, 3, 1))

  plot(x0, y0, pch = 16, col = "gray50",
       xlab = "DOY", ylab = "NDVI",
       main = paste("UID", unique(growing_seasons$UID),
                    "- Season", unique(growing_seasons$season)))

  if (show_ci) {
    polygon(c(doy, rev(doy)), c(ci_lo, rev(ci_hi)),
            col = rgb(0, 0.5, 0, 0.2), border = NA)
  }

  lines(doy, fitted_curve, col = "darkgreen", lwd = 2)
  abline(v = peak_doy, col = "darkgreen", lty = 2)

  if (show_transitions) {
    abline(v = transition_doys, col = "blue", lty = 2, lwd = 1.5)
        text(x = transition_doys,
         y = max(y0, na.rm = TRUE),
         labels = c(paste0("Greenup: ",    Greenup_doy),
                    paste0("Maturity: ",   Maturity_doy),
                    paste0("Senescence: ", Senescence_doy),
                    paste0("Dormancy: ",   Dormancy_doy)),
         col = "blue", cex = 0.7, srt = 90, adj = c(1.1, -0.3))
  }

  if (show_sos_eos) {
    abline(v = c(SOS_doy, EOS_doy), col = "red", lty = 2, lwd = 1.5)
        text(x = c(SOS_doy, EOS_doy),
         y = max(y0, na.rm = TRUE) * 0.9,
         labels = c(paste0("SOS: ", SOS_doy),
                    paste0("EOS: ", EOS_doy)),
         col = "red", cex = 0.7, srt = 90, adj = c(1.1, -0.3))
  }

  if (show_transitions | show_sos_eos) {
    legend("topright",
           legend = c(
             if (show_transitions) "Inflection",
             if (show_sos_eos)     "SOS/EOS",
             "Peak NDVI"),
           col = c(
             if (show_transitions) "blue",
             if (show_sos_eos)     "red",
             "darkgreen"),
           lty = 2, lwd = 1.5, cex = 0.7, bty = "n")
  }

  if (show_kprime) {
    plot(doy_Kp, Kprime, type = "l", col = "purple", lwd = 2,
         xlab = "DOY", ylab = "K' (Rate of Curvature Change)",
         main = "Rate of Change of Curvature (K')")
    abline(h = 0, lty = 2, col = "gray50")
    if (show_transitions) abline(v = transition_doys,      col = "blue", lty = 2, lwd = 1.5)
    if (show_sos_eos)     abline(v = c(SOS_doy, EOS_doy), col = "red",  lty = 2, lwd = 1.5)
    par(mfrow = c(1, 1))
  }
}

# plot_annual_curve(seasons[[2]], ndvi_obs = ndvi_normalized , show_kprime = TRUE, show_transitions = TRUE) #use example

```


```{r}

pheno_metrics <- function(location, ndvi_data) {
  ndvi_data %>%
    filter(UID == location) %>% 
    mutate(ndvi_normalized = despike(ndvi_normalized, "median", n = 2, k = 5)) -> extracts_samp
  
  growing_season(extracts_samp, ndvi_obs = ndvi_normalized, maxtroughhight = .4) -> seasons
  
  map(seasons, possibly(~fit_annual_curve(.x, ndvi_obs = ndvi_normalized), otherwise = NULL)) %>%
    compact() %>%
    bind_rows()
}

```

## Start of the loop

```{r, warning=FALSE}

normalized_ndvi_extracts %>% 
  select(UID) %>% 
  distinct() %>% 
  slice_sample(n = 100) %>% 
  pull() -> uids

results_list <- list()

for (i in seq_along(uids)) {
  current_metrics <- pheno_metrics(uids[i], ndvi_data = normalized_ndvi_extracts)
  results_list[[i]] <- as.data.frame(current_metrics)
}

bind_rows(results_list)

```




