---
title: "Mapping Final Output"
format: html
editor: visual
---

```{r}

library(tidyverse)
library(leaflet)

```


```{r}

read_rds("../data/processed_trees_ndvi_lc_climate.rds") -> tree_ldc_metrics_climate 

```

## Mapping final outcomes to check the distribution of species

```{r}

tree_ldc_metrics_climate %>%
  group_by(UID, species_common, x_long, y_lat) %>%
  summarise(n = n()) -> final_sample

color_palette <- c("#e6194B", "#3cb44b", "#ffe119", "#4363d8", "#f58231",
                   "#911eb4", "#42d4f4", "#f032e6", "#bfef45", "#fabed4",
                   "#469990", "#dcbeff", "#9A6324", "#fffac8", "#800000",
                   "#aaffc3", "#808000", "#ffd8b1", "#000075", "#a9a9a9")

# Create the mapping function using your palette
pal <- colorFactor(palette = color_palette, domain = final_sample$species_common)

leaflet(final_sample) %>%
  addTiles() %>%
  addCircleMarkers(
    lng         = ~x_long,
    lat         = ~y_lat,
    color       = ~pal(species_common),
    fillColor   = ~pal(species_common),
    fillOpacity = 0.8,
    radius      = 1,
    popup       = ~species_common
  ) %>%
  addLegend(
    position = "bottomright",
    pal      = pal,
    values   = ~species_common,
    title    = "Species"
  )

```

```{r}

tree_ldc_metrics_climate %>%
  group_by(species_botanic) %>%
  summarise(n = n()) 


```


