---
title: "Plotting species growing seasons"
format: html
editor: visual
---

```{r}

library(tidyverse)

```

```{r}

read_rds("../data/processed_trees_ndvi_lc_climate.rds")%>%
    filter(year < 2025, 
           condition %in% c("Fair", "Good", "Excellent"))  -> tree_ldc_metrics_climate 

```

```{r}

elmore_curve <- function(m1 = 0.15, m2 = 0.75, m3, m4, m5, m6, m7 = 0, t) {
  m1 + (m2 - m7 * t) * ((1/(1+exp((m3-t)/m4))) - (1/(1+exp((m5-t)/m6))))
}


tree_ldc_metrics_climate %>% 
  group_by(species_common, year) %>% 
  summarise(across(Greenup_doy:Peak_NDVI_doy, ~ mean(.x, na.rm = TRUE))) %>% 
  rowwise() %>% 
  mutate(est = list(tibble(doy = 1:365,
                           ndvi = elmore_curve(m3 = Greenup_doy,
                                               m4 = (Maturity_doy - Greenup_doy) / 4.4,
                                               m5 = Senescence_doy,
                                               m6 = (Dormancy_doy - Senescence_doy) / 4.4,
                                               t = 1:365)))) %>% 
  unnest(est) -> species_est

tree_ldc_metrics_climate %>%
  group_by(year) %>%
  summarise(across(Greenup_doy:Peak_NDVI_doy,
                   ~ mean(.x, na.rm = TRUE),
                   .names = "year_{.col}")) %>% 
  rowwise() %>% 
  mutate(est = list(tibble(doy = 1:365,
                           ndvi = elmore_curve(m3 = year_Greenup_doy,
                                               m4 = (year_Maturity_doy - year_Greenup_doy) / 4.4,
                                               m5 = year_Senescence_doy,
                                               m6 = (year_Dormancy_doy - year_Senescence_doy) / 4.4,
                                               t = 1:365)))) %>% 
  unnest(est) %>% 
  rename_with(~ str_remove(.x, "^year_")) %>%
  mutate(species_common = "average") -> year_est

bind_rows(year_est, species_est) %>% 
  filter(species_common != "average") %>% 
  ggplot(aes(x = doy, y = ndvi, color = species_common)) +
  geom_line(data = year_est 
            %>% select(-species_common), 
            color = "black", linewidth = 1, linetype = "dashed") +
  geom_line() +
  coord_cartesian(xlim = c(225, 325))+
  facet_grid(species_common ~ year)+
  #theme_classic()+
  theme(legend.position = "none",
        strip.text.y = element_text(angle = 0))

```

```{r}

tree_ldc_metrics_climate %>% 
  select(year, species_common, Greenup_doy:Peak_NDVI_doy) %>% 
  pivot_longer(cols = Greenup_doy:Peak_NDVI_doy, names_to = "pheno_metric", values_to = "doy") %>% 
  filter(pheno_metric %in% c("Greenup_doy", "Maturity_doy", "Senescence_doy", "Dormancy_doy")) %>% 
  ggplot(aes(y = pheno_metric, x = doy, fill = species_common)) +
  geom_violin(draw_quantiles = 0.5) +
  facet_grid(~ year)
  
```

# Violin Plots

```{r}

pheno_metrics <- c("Greenup_doy", "Maturity_doy", "Senescence_doy", "Dormancy_doy")

species_year_violins_plots <- function(pheno_metric){
  tree_ldc_metrics_climate %>% 
    ggplot(aes(y = species_common, x = .data[[pheno_metric]])) +
    geom_violin(draw_quantiles = 0.5) +
    geom_vline(data = tree_ldc_metrics_climate %>% 
               group_by(year) %>% 
               summarise(median = median(.data[[pheno_metric]], na.rm = TRUE)),
             aes(xintercept = median), color = "red", linewidth = .5, 
             linetype = "dashed") +
    facet_grid(~ year)
  }


species_year_violins_plots("Greenup_doy")

#map(pheno_metrics, species_year_violins_plots)

```

```{r}

tree_ldc_metrics_climate %>% 
  ggplot(aes(x = impervious_30_90m, y = Greenup_doy, color = species_common))+
  geom_boxplot()

tree_ldc_metrics_climate %>% 
  ggplot(aes(x = impervious_30_90m, y = Maturity_doy))+
  geom_point()+
  geom_smooth()

tree_ldc_metrics_climate %>% 
  ggplot(aes(x = impervious_30_90m, y = Senescence_doy))+
  geom_point()+
  geom_smooth()

tree_ldc_metrics_climate %>% 
  ggplot(aes(x = impervious_30_90m, y = Dormancy_doy))+
  geom_point()+
  geom_smooth()

tree_ldc_metrics_climate %>% 
  ggplot(aes(x = impervious_30m, y = Greenup_doy))+
  geom_point()+
  geom_smooth()

tree_ldc_metrics_climate %>% 
  ggplot(aes(x = impervious_30m, y = Maturity_doy))+
  geom_point()+
  geom_smooth()

tree_ldc_metrics_climate %>% 
  ggplot(aes(x = impervious_30m, y = Senescence_doy))+
  geom_point()+
  geom_smooth()

tree_ldc_metrics_climate %>% 
  ggplot(aes(x = impervious_30m, y = Dormancy_doy))+
  geom_point()+
  geom_smooth()

```





